<?xml version="1.0"?>
<robot name="limpeza" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="macros/link_geometry.urdf.xacro" />
  <xacro:include filename="macros/properties.urdf.xacro" />

  <xacro:include filename="macros/parts/base.urdf.xacro" />
  <xacro:include filename="macros/parts/wheel.urdf.xacro" />

  <xacro:include filename="simulation/gazebo_base.urdf.xacro" />
  <xacro:include filename="simulation/gazebo_laser.urdf.xacro" />
  <xacro:include filename="simulation/gazebo_camera.urdf.xacro" />
  <xacro:include filename="simulation/imu.urdf.xacro"/>

  <!-- Robot -->
  
  <xacro:base name="base_link"/>
  <xacro:wheel name="left_wheel">
    <origin xyz="-0.048 0.048 ${-wheel_radius -body_length/2}" rpy="0 0 0"/>
  </xacro:wheel>
  <xacro:wheel name="right_wheel">
    <origin xyz="-0.048 -0.048 ${-wheel_radius -body_length/2}" rpy="0 0 0"/>
  </xacro:wheel>
  <xacro:wheel name="front_wheel">
    <origin xyz="0.048 0 ${-wheel_radius -body_length/2}" rpy="0 0 0"/>
  </xacro:wheel>


  <!-- IMU -->
  <xacro:imu name="imu" parent="base_link">
    <origin xyz="0.0 0.0 0.055" rpy="0 0 0"/>
  </xacro:imu>



  <!-- Plugins -->
  <xacro:gazebo_base/>
  <xacro:gazebo_laser reference="base_scan"/>
</robot>
