<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="PI"             value="3.14159265" />

  <xacro:property name="robot_mass"      value="3" />

  <xacro:property name="body_mass"      value="${70 * robot_mass/100}" />
  <xacro:property name="body_radius"    value="0.115" />
  <xacro:property name="body_length"    value="0.2" />

  <xacro:property name="laser_mass"      value="${15 * robot_mass/100}" />
  <xacro:property name="laser_radius"    value="${body_radius/3}" />
  <xacro:property name="laser_length"    value="0.025" />

  <xacro:property name="wheel_mass"      value="${5 * robot_mass/100}" />
  <xacro:property name="wheel_radius"    value="0.0335" />

</robot>
