<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="base" params="name">

    <!-- link: base_footprint -->
    <link name='base_footprint'/>

    <!-- joint: base_footprint -> base -->
    <joint name="joint_base_footprint_to_base" type="fixed">
      <origin xyz="0 0 ${(wheel_radius)*2}" rpy="0 0 0"/>
      <parent link="base_footprint"/>
      <child link="base_link"/>
    </joint>

    <!-- link: base -->
    <link name="${name}">
      <xacro:create_cylinder m="${body_mass}" r="${body_radius}" l="${body_length}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:create_cylinder>
    </link>

  <joint name="base_to_laser" type="fixed">
    <origin xyz="0 0 ${body_length/2 + laser_length/2}" rpy="0 0 0"/>
    <parent link="base_scan"/>
    <child link="${name}"/>
  </joint>
  <link name="base_scan">
    <xacro:create_cylinder m="${laser_mass}" r="${laser_radius}" l="${laser_length}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:create_cylinder>
  </link>
  
  </xacro:macro>

</robot>
