<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="PI"             value="3.14159265" />

  <xacro:property name="robot_mass"      value="10" />

  <xacro:property name="body_mass"      value="${10 * robot_mass/100}" />
  <xacro:property name="body_radius"    value="0.3" />
  <xacro:property name="body_length"    value="0.4" />

  <xacro:property name="laser_mass"      value="${50 * robot_mass/100}" />
  <xacro:property name="laser_radius"    value="${body_radius}" />
  <xacro:property name="laser_length"    value="0.025" />

  <xacro:property name="holder_mass"      value="${5 * robot_mass/100}" />
  <xacro:property name="holder_radius"    value="0.02" />
  <xacro:property name="holder_length"    value="0.2" />
  <xacro:property name="holder_xy"        value="0.12" />
  <xacro:property name="holder_z"         value="0.11" />

  <xacro:property name="plate_mass"      value="${4 * robot_mass/100}" />
  <xacro:property name="plate_radius"    value="${body_radius}" />
  <xacro:property name="plate_length"    value="0.02" />

  <xacro:property name="screen_mass"      value="${1 * robot_mass/100}" />
  <xacro:property name="screen_x"         value="0.05" />
  <xacro:property name="screen_y"         value="0.2" />
  <xacro:property name="screen_z"         value="0.2" />

  <xacro:property name="camera_mass"      value="${1 * robot_mass/100}" />
  <xacro:property name="camera_x"         value="0.025" />
  <xacro:property name="camera_y"         value="0.025" />
  <xacro:property name="camera_z"         value="0.02" />

  <xacro:property name="wheel_mass"      value="${5 * robot_mass/100}" />
  <xacro:property name="wheel_radius"    value="${body_radius/4}" />

</robot>
